server: http://localhost:4224

load:
- js/underscore.1.3.1.js
- js/jquery-1.7.1.js
- js/modernizr-2.5.3.js
- js/polyfilled-localStorage.js
- js/backbone.0.9.1.js
- js/my-templates.js
- js/my.js
#- js/my-router.js

#exclude:
#- js/my-router.js

test:
- test/usestrict-test.js
- test/underscore-template-test.js
- test/dom-test.js
- test/backbone-model-test.js
- test/backbone-view-test.js

serve:
- test/cssresource.css
- content.partial.html

# Coverage, but not particularly supported in Windows...
#plugin:
#- name: "coverage"
#   jar: "test/plugins/coverage-1.3.4.b.jar"
#   module: "com.google.jstestdriver.coverage.CoverageModule"
